export const GET_ARTICLS = 'GET_ARTICLS';
export const GET_ONE = 'GET_ONE';
export const SAVE_ARTICL = 'SAVE_ARTICL';
export const DELETE_ARTICL = 'DELETE_ARTICL';
export const GET_COMMENTS = 'GET_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const SHOW_LOADING_INDICATOR = 'SHOW_LOADING_INDICATOR';
export const HIDE_LOADING_INDICATOR = 'HIDE_LOADING_INDICATOR';
